# Generated by Django 6.0.3 on 2026-04-04 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('message', models.TextField()),
                ('mode', models.CharField(choices=[('simple', 'Simple'), ('deep', 'Deep')], default='simple', max_length=16)),
                ('response_mode', models.CharField(choices=[('llm', 'LLM'), ('fallback', 'Fallback')], default='fallback', max_length=16)),
                ('helpful', models.BooleanField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='guide_api.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
