# Generated by Django 6.0.3 on 2026-04-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0002_responsefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
