# Generated by Django 6.0.3 on 2026-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0004_usersubscription_dailyaskusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(choices=[('api', 'API'), ('chat_ui', 'Chat UI')], max_length=16)),
                ('mode', models.CharField(choices=[('simple', 'Simple'), ('deep', 'Deep')], max_length=16)),
                ('outcome', models.CharField(choices=[('served', 'Served'), ('blocked_safety', 'Blocked by safety'), ('blocked_quota', 'Blocked by quota')], max_length=32)),
                ('response_mode', models.CharField(blank=True, choices=[('llm', 'LLM'), ('fallback', 'Fallback')], max_length=16)),
                ('retrieval_mode', models.CharField(blank=True, max_length=32)),
                ('plan', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
