# Generated by Django 6.0.3 on 2026-04-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0006_savedreflection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(choices=[('api', 'API'), ('chat_ui', 'Chat UI')], max_length=16)),
                ('event_type', models.CharField(choices=[('shown', 'Shown'), ('clicked', 'Clicked')], max_length=16)),
                ('intent', models.CharField(max_length=32)),
                ('prompt', models.CharField(max_length=255)),
                ('mode', models.CharField(default='simple', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
