# Generated by Django 6.0.3 on 2026-04-06 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0008_engagementevent_userengagementprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='payment_currency',
            field=models.CharField(blank=True, choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuoteArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_reference', models.CharField(max_length=16)),
                ('quote_text', models.TextField()),
                ('quote_language', models.CharField(default='en', max_length=8)),
                ('style', models.CharField(choices=[('divine', 'Divine - golden temple aesthetic'), ('minimal', 'Minimal - clean modern design'), ('nature', 'Nature - forest and lotus imagery'), ('cosmic', 'Cosmic - stars and universe theme')], default='divine', max_length=16)),
                ('background_color', models.CharField(default='#1a1a2e', max_length=16)),
                ('text_color', models.CharField(default='#ffd700', max_length=16)),
                ('font_style', models.CharField(default='serif', max_length=32)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_arts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
