# Generated by Django 6.0.3 on 2026-04-08 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0009_usersubscription_payment_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerseSynthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('overview_en', models.TextField(blank=True)),
                ('overview_hi', models.TextField(blank=True)),
                ('commentary_consensus_en', models.TextField(blank=True)),
                ('commentary_consensus_hi', models.TextField(blank=True)),
                ('life_application_en', models.TextField(blank=True)),
                ('life_application_hi', models.TextField(blank=True)),
                ('key_points_en', models.JSONField(blank=True, default=list)),
                ('key_points_hi', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='synthesis', to='guide_api.verse')),
            ],
            options={
                'ordering': ['verse__chapter', 'verse__verse'],
            },
        ),
    ]
