# Generated by Django 6.0.3 on 2026-04-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0010_versesynthesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='versesynthesis',
            name='generation_source',
            field=models.CharField(choices=[('llm', 'LLM'), ('fallback', 'Fallback')], default='fallback', max_length=16),
        ),
    ]
