# Generated by Django 6.0.3 on 2026-04-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0011_versesynthesis_generation_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestChatIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('conversations_started', models.PositiveIntegerField(default=0)),
                ('total_asks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
