# Generated by Django 6.0.3 on 2026-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0014_requestquotasettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAudienceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_source', models.CharField(choices=[('chat_ui', 'Chat UI'), ('seo_index', 'SEO Index'), ('seo_topic', 'SEO Topic')], max_length=16)),
                ('last_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
