# Generated by Django 6.0.3 on 2026-04-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0015_webaudienceprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('landing_view', 'Landing View'), ('starter_click', 'Starter Click'), ('share_click', 'Share Click'), ('copy_link_click', 'Copy Link Click'), ('ask_submit', 'Ask Submit')], max_length=24)),
                ('source', models.CharField(choices=[('chat_ui', 'Chat UI'), ('seo_index', 'SEO Index'), ('seo_topic', 'SEO Topic')], max_length=16)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='webaudienceprofile',
            name='first_source',
            field=models.CharField(blank=True, choices=[('chat_ui', 'Chat UI'), ('seo_index', 'SEO Index'), ('seo_topic', 'SEO Topic')], max_length=16),
        ),
        migrations.AddField(
            model_name='webaudienceprofile',
            name='first_utm_campaign',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='webaudienceprofile',
            name='first_utm_medium',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='webaudienceprofile',
            name='first_utm_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='webaudienceprofile',
            name='last_utm_campaign',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='webaudienceprofile',
            name='last_utm_medium',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='webaudienceprofile',
            name='last_utm_source',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
