# Generated by Django 6.0.3 on 2026-04-12 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0016_growthevent_webaudienceprofile_first_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.TextField()),
                ('guidance', models.TextField()),
                ('verse_references', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=4)),
                ('user_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
