# Generated by Django 6.0.3 on 2026-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0017_sharedanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedanswer',
            name='actions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sharedanswer',
            name='meaning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sharedanswer',
            name='reflection',
            field=models.TextField(blank=True),
        ),
    ]
