# Generated by Django 6.0.3 on 2026-04-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0018_sharedanswer_actions_sharedanswer_meaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquotasettings',
            name='free_deep_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestquotasettings',
            name='free_monthly_ask_limit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='requestquotasettings',
            name='plus_daily_ask_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestquotasettings',
            name='plus_deep_monthly_limit',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='requestquotasettings',
            name='plus_limit_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestquotasettings',
            name='plus_monthly_ask_limit',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='requestquotasettings',
            name='pro_deep_monthly_limit',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='requestquotasettings',
            name='pro_monthly_ask_limit',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='requestquotasettings',
            name='pro_daily_ask_limit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
