# Generated by Django 6.0.3 on 2026-04-12 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0019_requestquotasettings_free_deep_mode_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro')], default='free', max_length=16),
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro')], default='free', max_length=16)),
                ('payment_status', models.CharField(choices=[('created', 'Created'), ('verified', 'Verified'), ('captured', 'Captured'), ('failed', 'Failed')], default='created', max_length=16)),
                ('tax_treatment', models.CharField(choices=[('domestic_taxable', 'Domestic taxable'), ('export_lut', 'Export under LUT'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('is_international', models.BooleanField(default=False)),
                ('billing_name', models.CharField(blank=True, max_length=120)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('billing_country_code', models.CharField(blank=True, max_length=2)),
                ('billing_country_name', models.CharField(blank=True, max_length=80)),
                ('billing_state', models.CharField(blank=True, max_length=80)),
                ('billing_city', models.CharField(blank=True, max_length=80)),
                ('billing_postal_code', models.CharField(blank=True, max_length=20)),
                ('billing_address', models.TextField(blank=True)),
                ('currency', models.CharField(blank=True, choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], max_length=3)),
                ('amount_minor', models.PositiveIntegerField(default=0)),
                ('amount_major', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('invoice_reference', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_order_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payment_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='guide_api.usersubscription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
