# Generated by Django 6.0.3 on 2026-04-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0020_alter_usersubscription_plan_billingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestchatidentity',
            name='daily_asks_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestchatidentity',
            name='daily_asks_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
