# Generated by Django 6.0.3 on 2026-04-18 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0022_community_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SadhanaProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('philosophy_blurb', models.TextField(blank=True, help_text='Optional wellness / non-medical disclaimer shown with the program.')),
                ('duration_days', models.PositiveSmallIntegerField(default=30)),
                ('estimated_minutes_per_day', models.PositiveSmallIntegerField(default=15)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('free_sample_day_number', models.PositiveSmallIntegerField(default=1, help_text='Day index (1-based) available without purchase for preview.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SadhanaEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_starts_at', models.DateTimeField()),
                ('access_ends_at', models.DateTimeField()),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sadhana_enrollments', to='guide_api.billingrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadhana_enrollments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='guide_api.sadhanaprogram')),
            ],
        ),
        migrations.CreateModel(
            name='SadhanaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('intention', models.TextField(blank=True, help_text='Closing intention / living-the-mantra cue for the day.')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='guide_api.sadhanaprogram')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='SadhanaStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('step_type', models.CharField(choices=[('warmup_yoga', 'Warm-up yoga'), ('pranayama', 'Prānāyāma'), ('bhakti', 'Bhakti / remembrance'), ('mantra', 'Mantra chanting'), ('integration', 'Living the mantra')], max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='guide_api.sadhanaday')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='SadhanaDayCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='guide_api.sadhanaday')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_days', to='guide_api.sadhanaenrollment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'day'), name='unique_sadhana_enrollment_day_completion')],
            },
        ),
        migrations.AddConstraint(
            model_name='sadhanaenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'program'), name='unique_sadhana_user_program'),
        ),
        migrations.AddConstraint(
            model_name='sadhanaday',
            constraint=models.UniqueConstraint(fields=('program', 'day_number'), name='unique_sadhana_program_day_number'),
        ),
        migrations.AddConstraint(
            model_name='sadhanastep',
            constraint=models.UniqueConstraint(fields=('day', 'sequence'), name='unique_sadhana_day_sequence'),
        ),
    ]
