# Generated by Django 6.0.3 on 2026-04-18 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0023_sadhana_programs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sadhanadaycompletion',
            name='unique_sadhana_enrollment_day_completion',
        ),
        migrations.AddField(
            model_name='sadhanadaycompletion',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Used when marking free-sample days without paid enrollment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sadhana_day_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sadhanadaycompletion',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_days', to='guide_api.sadhanaenrollment'),
        ),
        migrations.AddConstraint(
            model_name='sadhanadaycompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('enrollment__isnull', False)), fields=('enrollment', 'day'), name='unique_sadhana_enrollment_day_completion'),
        ),
        migrations.AddConstraint(
            model_name='sadhanadaycompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('enrollment__isnull', True), ('user__isnull', False)), fields=('user', 'day'), name='unique_sadhana_user_day_sample_completion'),
        ),
        migrations.AddConstraint(
            model_name='sadhanadaycompletion',
            constraint=models.CheckConstraint(condition=models.Q(('enrollment__isnull', False), ('user__isnull', False), _connector='OR'), name='sadhana_completion_has_actor'),
        ),
    ]
