# Generated by Django 6.0.3 on 2026-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0025_notificationdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='payment_status',
            field=models.CharField(choices=[('created', 'Created'), ('verified', 'Verified'), ('captured', 'Captured'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=16),
        ),
    ]
