# Generated by Django 6.0.3 on 2026-04-27 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0028_userengagementprofile_reminder_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReadingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_chapter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_verse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verses_seen', models.JSONField(blank=True, default=list)),
                ('last_read_date', models.DateField(blank=True, null=True)),
                ('read_streak', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeditationSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_mood', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pre_stress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pre_note', models.TextField(blank=True, max_length=2000)),
                ('post_mood', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post_stress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post_note', models.TextField(blank=True, max_length=2000)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('program_slug', models.SlugField(blank=True, max_length=96)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_session_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='guide_api_m_user_id_a951b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PracticeLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_on', models.DateField()),
                ('entry_type', models.CharField(choices=[('japa_rounds', 'Japa (mala rounds)'), ('meditation_minutes', 'Meditation minutes'), ('read_minutes', 'Reading minutes')], max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('mantra_label', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_on', '-created_at'],
                'indexes': [models.Index(fields=['user', 'logged_on'], name='guide_api_p_user_id_9933ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerseUserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('body', models.TextField(blank=True, max_length=12000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'chapter', 'verse'), name='unique_user_verse_note')],
            },
        ),
    ]
