# Generated by Django 6.0.3 on 2026-04-27 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0029_practice_reading_verse_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JapaDailyCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('malas_completed', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JapaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('pause_started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_seconds', models.PositiveIntegerField(default=0)),
                ('reported_malas', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JapaCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('focus_label', models.CharField(blank=True, help_text='Iṣṭa / deity / form (free text).', max_length=120)),
                ('mantra_label', models.CharField(blank=True, max_length=120)),
                ('daily_target_malas', models.PositiveSmallIntegerField(default=1)),
                ('started_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('fulfilled', 'Fulfilled'), ('archived', 'Archived')], default='active', max_length=16)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japa_commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='practicelogentry',
            name='japa_commitment',
            field=models.ForeignKey(blank=True, help_text='When set, this row syncs one calendar day of japa for that personal track.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_log_entries', to='guide_api.japacommitment'),
        ),
        migrations.AddIndex(
            model_name='practicelogentry',
            index=models.Index(fields=['user', 'japa_commitment', 'logged_on'], name='guide_api_p_user_id_cabf21_idx'),
        ),
        migrations.AddField(
            model_name='japadailycompletion',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_completions', to='guide_api.japacommitment'),
        ),
        migrations.AddField(
            model_name='japasession',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='guide_api.japacommitment'),
        ),
        migrations.AddField(
            model_name='japasession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japa_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='japadailycompletion',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_completions', to='guide_api.japasession'),
        ),
        migrations.AddIndex(
            model_name='japacommitment',
            index=models.Index(fields=['user', 'status'], name='guide_api_j_user_id_a2a1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='japasession',
            index=models.Index(fields=['user', 'status'], name='guide_api_j_user_id_12a5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='japasession',
            index=models.Index(fields=['commitment', '-started_at'], name='guide_api_j_commitm_a53996_idx'),
        ),
        migrations.AddConstraint(
            model_name='japadailycompletion',
            constraint=models.UniqueConstraint(fields=('commitment', 'date'), name='unique_japa_commitment_date'),
        ),
    ]
