# Generated by Django 6.0.3 on 2026-04-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0030_japa_commitments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadhanastep',
            name='requires_standing',
            field=models.BooleanField(default=False, help_text='If true, UI can warn users who practice seated only.'),
        ),
        migrations.AddField(
            model_name='sadhanastep',
            name='safety_tier',
            field=models.CharField(choices=[('gentle', 'Gentle'), ('moderate', 'Moderate'), ('intense', 'Intense — extra care')], default='gentle', max_length=16),
        ),
        migrations.AddField(
            model_name='sadhanastep',
            name='subtitle_tracks',
            field=models.JSONField(blank=True, default=list, help_text='List of {language, label, format, url, is_default?} for WebVTT/SRT captions.'),
        ),
        migrations.AddField(
            model_name='sadhanastep',
            name='timed_cues',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of {t_ms, text} for on-screen follow-along (e.g. mantra lines).'),
        ),
        migrations.AlterField(
            model_name='sadhanastep',
            name='step_type',
            field=models.CharField(choices=[('warmup_yoga', 'Warm-up yoga'), ('yoga_flow', 'Yoga flow'), ('pranayama', 'Prānāyāma'), ('breath_awareness', 'Breath awareness'), ('bhakti', 'Bhakti / remembrance'), ('mantra', 'Mantra chanting'), ('naam_japa_guided', 'Nām japa (guided)'), ('kirtan_listen', 'Kīrtan (listen / follow)'), ('bhajan_listen', 'Bhajan (listen / follow)'), ('silent_sit', 'Silent sitting'), ('soundscape', 'Soundscape / ambience'), ('affirmation_sankalpa', 'Affirmation / saṅkalpa'), ('teaching_dharma', 'Teaching / śāstra moment'), ('subtle_body_guided', 'Subtle body (guided — advanced)'), ('integration', 'Living the mantra / integration')], max_length=32),
        ),
    ]
