# Generated by Django 6.0.3 on 2026-04-27 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0031_sadhana_step_media_captions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('category', models.CharField(blank=True, help_text='Optional grouping for UI facets (e.g. deity, lineage).', max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='PracticeWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('philosophy_blurb', models.TextField(blank=True, help_text='Optional wellness / non-medical disclaimer shown with the flow.')),
                ('access_mode', models.CharField(choices=[('free_public', 'Free — all signed-in users'), ('pro_included', 'Included with active Pro'), ('purchase_required', 'Purchase required (any plan)')], db_index=True, default='free_public', max_length=24)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Highlight in Meditate / practice hub when true.')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('estimated_total_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purchase_notes', models.CharField(blank=True, help_text='Short copy when purchase is required (checkout wiring is separate).', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PracticeWorkflowEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_starts_at', models.DateTimeField()),
                ('access_ends_at', models.DateTimeField(blank=True, help_text='Null means no fixed end (lifetime / open window).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_workflow_enrollments', to='guide_api.billingrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_workflow_enrollments', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='guide_api.practiceworkflow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'workflow'), name='unique_practice_workflow_user_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='PracticeWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('step_type', models.CharField(choices=[('warmup_yoga', 'Warm-up yoga'), ('yoga_flow', 'Yoga flow'), ('pranayama', 'Prānāyāma'), ('breath_awareness', 'Breath awareness'), ('bhakti', 'Bhakti / remembrance'), ('mantra', 'Mantra chanting'), ('naam_japa_guided', 'Nām japa (guided)'), ('kirtan_listen', 'Kīrtan (listen / follow)'), ('bhajan_listen', 'Bhajan (listen / follow)'), ('silent_sit', 'Silent sitting'), ('soundscape', 'Soundscape / ambience'), ('affirmation_sankalpa', 'Affirmation / saṅkalpa'), ('teaching_dharma', 'Teaching / śāstra moment'), ('subtle_body_guided', 'Subtle body (guided — advanced)'), ('integration', 'Living the mantra / integration')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subtitle_tracks', models.JSONField(blank=True, default=list, help_text='List of {language, label, format, url, is_default?} for WebVTT/SRT captions.')),
                ('timed_cues', models.JSONField(blank=True, default=list, help_text='Optional list of {t_ms, text} for on-screen follow-along.')),
                ('safety_tier', models.CharField(choices=[('gentle', 'Gentle'), ('moderate', 'Moderate'), ('intense', 'Intense — extra care')], default='gentle', max_length=16)),
                ('requires_standing', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='workflow_steps', to='guide_api.practicetag')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='guide_api.practiceworkflow')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'sequence'), name='unique_practice_workflow_step_sequence')],
            },
        ),
    ]
