# Generated by Django 6.0.3 on 2026-04-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0032_practice_workflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceworkflow',
            name='purchase_access_days',
            field=models.PositiveIntegerField(blank=True, help_text='Access window after purchase; null = lifetime (no fixed end).', null=True),
        ),
        migrations.AddField(
            model_name='practiceworkflow',
            name='purchase_price_minor_inr',
            field=models.PositiveIntegerField(blank=True, help_text='Razorpay order amount (paise) when access_mode is purchase_required.', null=True),
        ),
        migrations.AddField(
            model_name='practiceworkflow',
            name='purchase_price_minor_usd',
            field=models.PositiveIntegerField(blank=True, help_text='Razorpay order amount (cents) when access_mode is purchase_required.', null=True),
        ),
    ]
