# Generated by Django 6.0.3 on 2026-04-28 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0033_practice_workflow_purchase_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGitaSequenceJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=16)),
                ('next_chapter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_verse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intention_text', models.CharField(blank=True, help_text='Optional sankalpa / note when starting the path.', max_length=2000)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gita_sequence_journey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gita sequence journey',
                'verbose_name_plural': 'Gita sequence journeys',
            },
        ),
    ]
