# Generated by Django 6.0.3 on 2026-05-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0035_performance_indexes'),
        ('guide_api', '0036_response_feedback_quality_fields'),
    ]

    operations = [
    ]
