# Generated by Django 6.0.3 on 2026-05-01 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0037_merge_20260501_1703'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GratitudeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_1', models.CharField(blank=True, max_length=300)),
                ('item_2', models.CharField(blank=True, max_length=300)),
                ('item_3', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MoodCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy 😊'), ('grateful', 'Grateful 🥰'), ('relaxed', 'Relaxed 😌'), ('content', 'Content 🙂'), ('excited', 'Excited 😛'), ('tired', 'Tired 😴'), ('unsure', 'Unsure 😕'), ('bored', 'Bored 😑'), ('anxious', 'Anxious 😬'), ('angry', 'Angry 😤'), ('stressed', 'Stressed 😣'), ('sad', 'Sad 😢')], db_index=True, max_length=16)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='askevent',
            name='askevent_user_mode_outcome_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingrecord',
            name='billing_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='conv_userid_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='japadailycompletion',
            name='japacomplete_commit_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='msg_conv_role_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedreflection',
            name='savedref_user_created_idx',
        ),
        migrations.AddField(
            model_name='gratitudeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gratitudeentry',
            index=models.Index(fields=['user', 'date'], name='gratitude_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='gratitudeentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_gratitude_user_date'),
        ),
        migrations.AddIndex(
            model_name='moodcheckin',
            index=models.Index(fields=['user', 'date'], name='mood_user_date_idx'),
        ),
    ]
