# Generated by Django 6.0.3 on 2026-05-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0039_streakfreeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='userengagementprofile',
            name='onboarding_goal',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
