# Generated by Django 6.0.3 on 2026-05-04 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0040_onboarding_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationPracticeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True, help_text='Full devotional description shown to users.')),
                ('category', models.CharField(choices=[('japa', 'Naam Japa'), ('meditation', 'Meditation'), ('breath', 'Breathwork / Pranayama'), ('mantra', 'Mantra'), ('sadhana', 'Sadhana'), ('other', 'Other')], db_index=True, default='other', max_length=24)),
                ('icon_url', models.URLField(blank=True, help_text='Optional square icon/artwork URL.')),
                ('cover_url', models.URLField(blank=True, help_text='Banner/cover image for detail screen.')),
                ('default_access_level', models.CharField(choices=[('free', 'Free — all signed-in users'), ('plus', 'Plus+ required'), ('pro', 'Pro required')], default='free', help_text='Minimum plan required to access this practice type.', max_length=16)),
                ('counts_as_sadhana', models.BooleanField(default=True, help_text='Practice-mode sessions are counted in sadhana streak and insights.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MeditationPracticeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('text', 'Text / Reading'), ('guided', 'Guided session')], default='audio', max_length=16)),
                ('media_url', models.URLField(blank=True, help_text='Direct audio/video URL.')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('teacher', models.CharField(blank=True, help_text='Voice / teacher / source attribution.', max_length=120)),
                ('mantra_name', models.CharField(blank=True, help_text='Primary mantra or divine name featured in this content.', max_length=200)),
                ('supports_loop', models.BooleanField(default=False, help_text='Can be looped during practice-together mode.')),
                ('mode', models.CharField(choices=[('learn', 'Learn only'), ('practice', 'Practice together'), ('both', 'Learn or practice')], default='both', max_length=12)),
                ('access_level', models.CharField(choices=[('free', 'Free — all signed-in users'), ('plus', 'Plus+ required'), ('pro', 'Pro required'), ('purchase', 'One-time purchase')], db_index=True, default='free', max_length=16)),
                ('purchase_price_minor_inr', models.PositiveIntegerField(blank=True, help_text='Price in paise (INR × 100) for one-time purchase.', null=True)),
                ('purchase_price_minor_usd', models.PositiveIntegerField(blank=True, help_text='Price in cents (USD × 100) for one-time purchase.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='guide_api.meditationpracticetype')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MeditationContentUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = lifetime access.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_content_unlocks', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='guide_api.meditationpracticecontent')),
            ],
            options={
                'ordering': ['-purchased_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'content'), name='unique_meditation_unlock')],
            },
        ),
        migrations.CreateModel(
            name='MeditationPracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('learn', 'Learn only'), ('practice', 'Practice together')], db_index=True, default='practice', max_length=12)),
                ('status', models.CharField(choices=[('started', 'In progress'), ('completed', 'Completed'), ('interrupted', 'Interrupted (app backgrounded)'), ('abandoned', 'Abandoned')], db_index=True, default='started', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Wall-clock elapsed seconds (may include idle time).')),
                ('tracked_seconds', models.PositiveIntegerField(default=0, help_text='Actively-tracked foreground seconds (app was in use).')),
                ('intention', models.CharField(blank=True, help_text='Sankalpa / intention for this sit.', max_length=500)),
                ('chosen_mantra', models.CharField(blank=True, max_length=200)),
                ('target_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('target_count', models.PositiveSmallIntegerField(blank=True, help_text='Target rounds/malas.', null=True)),
                ('used_mala', models.BooleanField(blank=True, null=True)),
                ('mood_before', models.CharField(blank=True, choices=[('1', 'Very low / troubled'), ('2', 'Low / distracted'), ('3', 'Neutral'), ('4', 'Calm / centred'), ('5', 'Very peaceful / elevated')], max_length=2)),
                ('mood_after', models.CharField(blank=True, choices=[('1', 'Very low / troubled'), ('2', 'Low / distracted'), ('3', 'Neutral'), ('4', 'Calm / centred'), ('5', 'Very peaceful / elevated')], max_length=2)),
                ('presence_rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5 self-rating of how present/focused the user felt.', null=True)),
                ('chanting_mode', models.CharField(blank=True, choices=[('aloud', 'Aloud'), ('whisper', 'Whisper'), ('mental', 'Mentally'), ('listen_along', 'Listened along'), ('mixed', 'Mixed')], max_length=16)),
                ('actual_count', models.PositiveSmallIntegerField(blank=True, help_text='Actual rounds/malas completed.', null=True)),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('internal_observation', models.CharField(blank=True, help_text='One thing noticed internally during the practice.', max_length=500)),
                ('reflection_note', models.TextField(blank=True, max_length=2000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='guide_api.meditationpracticecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_practice_sessions', to=settings.AUTH_USER_MODEL)),
                ('practice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='guide_api.meditationpracticetype')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='mps_user_started_idx'), models.Index(fields=['user', 'mode', 'status'], name='mps_user_mode_status_idx'), models.Index(fields=['practice_type', 'status'], name='mps_type_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='meditationpracticecontent',
            index=models.Index(fields=['practice_type', 'is_active', 'sort_order'], name='guide_api_m_practic_be357f_idx'),
        ),
    ]
