# Generated by Django 6.0.3 on 2026-05-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0041_meditation_practice_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationpracticetype',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image directly. Used when cover_url is empty.', upload_to='practice_covers/'),
        ),
        migrations.AlterField(
            model_name='meditationpracticetype',
            name='cover_url',
            field=models.URLField(blank=True, help_text='Banner/cover image URL (external CDN). Takes priority over cover_image.'),
        ),
    ]
