# Generated by Django 6.0.3 on 2026-05-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0042_add_cover_image_to_practice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='custom_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
