# Generated by Django 5.2.13 on 2026-04-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_exports_per_month', models.PositiveIntegerField(default=5, help_text='Max computation PDF exports per month for free users (Pro unlimited).')),
            ],
            options={
                'verbose_name_plural': 'Quota settings',
            },
        ),
    ]
