# Generated by Django 6.0.3 on 2026-05-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_quotasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='itr_export_credits',
            field=models.PositiveIntegerField(default=0, help_text='Prepaid export credits remaining from bundle purchases.'),
        ),
    ]
