# Generated by Django 6.0.3 on 2026-05-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_itr_export_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='itr_annual_exports_used',
            field=models.PositiveIntegerField(default=0, help_text='Exports consumed in the current annual plan cycle.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='itr_plan',
            field=models.CharField(blank=True, choices=[('', 'None'), ('essentials', 'Essentials — 40 exports/yr'), ('professional', 'Professional — 100 exports/yr')], default='', help_text='Active annual plan: essentials (40/yr) or professional (100/yr).', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='itr_plan_until',
            field=models.DateTimeField(blank=True, help_text='Annual plan valid until this instant (UTC).', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='itr_export_credits',
            field=models.PositiveIntegerField(default=0, help_text='Pay-as-you-go credits remaining (1 credit = 1 export, never expire).'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_until',
            field=models.DateTimeField(blank=True, help_text='(Legacy) Pro access valid until this instant (UTC).', null=True),
        ),
    ]
