services:
  - type: web
    name: bhagwat-gita-guide
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_HOSTS
        scope: run
        value: .onrender.com
