# Generated by Django 6.0.3 on 2026-05-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpayorder',
            name='bundle_key',
            field=models.CharField(blank=True, default='', help_text='ITR credit bundle: payg / essentials / professional', max_length=32),
        ),
        migrations.AddField(
            model_name='razorpayorder',
            name='credits_granted',
            field=models.PositiveIntegerField(default=0, help_text='Number of export credits added on payment success.'),
        ),
    ]
