# Generated by Django 6.0.3 on 2026-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_guest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorder',
            name='amount_paise',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
