# Generated by Django 6.0.3 on 2026-05-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_guestorder_amount_paise'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestorder',
            name='export_used',
            field=models.BooleanField(default=False),
        ),
    ]
