"""API route table for guide endpoints."""

from django.urls import path

from guide_api.practice_workflow_views import (
    PracticeTagListView,
    PracticeWorkflowDetailView,
    PracticeWorkflowListView,
    PracticeWorkflowMeView,
)
from guide_api.sadhana_views import (
    SadhanaDayCompleteView,
    SadhanaDayDetailView,
    SadhanaMeView,
    SadhanaProgramDetailView,
    SadhanaProgramListView,
)
from guide_api.gita_sequence_views import (
    GitaPathAbandonView,
    GitaPathAdvanceView,
    GitaPathPauseView,
    GitaPathResumeView,
    GitaPathStartView,
    GitaPathView,
)
from guide_api.japa_views import (
    JapaCommitmentDetailView,
    JapaCommitmentFulfillView,
    JapaCommitmentListCreateView,
    JapaSessionAbandonView,
    JapaSessionFinishDayView,
    JapaSessionPauseView,
    JapaSessionResumeView,
    JapaSessionStartView,
)
from guide_api.views import (
    AnalyticsEventIngestView,
    AnalyticsSummaryView,
    AskView,
    AskStreamView,
    ChatUIView,
    CommunityPostDetailView,
    CommunityPostListCreateView,
    ChapterDetailView,
    ChapterListView,
    ConversationHistoryView,
    ConversationListCreateView,
    ConversationMessagesView,
    ConversationDetailView,
    CreateOrderView,
    ChangePasswordView,
    DailyVerseView,
    DailyVerseHistoryView,
    EngagementProfileView,
    FeaturedQuotesView,
    FeedbackView,
    FollowUpGenerateView,
    GuestAskView,
    GuestHistoryResetView,
    GuestHistoryView,
    GuestRecentQuestionsView,
    ForgotPasswordView,
    GoogleAuthView,
    HealthView,
    LoginView,
    LogoutView,
    MantraView,
    MeditationSessionLogCreateView,
    MeView,
    NotificationDeviceDeleteView,
    NotificationDeviceListView,
    NotificationDeviceRegisterView,
    NotificationPreferencesView,
    PlanCatalogView,
    PlanUpdateView,
    PracticeLogListCreateView,
    PaymentHistoryView,
    PaymentStatusUpdateView,
    PaymentCheckoutBridgeView,
    ProfileUpdateView,
    QuoteArtStylesView,
    QuoteArtView,
    RazorpayWebhookView,
    ReadingStateView,
    ReadingVerseOpenView,
    RegisterView,
    ResetPasswordConfirmView,
    RetrievalEvalView,
    SavedReflectionDetailView,
    SavedReflectionListCreateView,
    SharedAnswerCreateView,
    SupportRequestView,
    StarterPromptsView,
    SupportTicketListView,
    SubscriptionStatusView,
    UserInsightsSummaryView,
    VerifyPaymentView,
    VerseDetailView,
    VerseSearchView,
    VerseUserNoteView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("starter-prompts/", StarterPromptsView.as_view(), name="starter-prompts"),
    path("plans/catalog/", PlanCatalogView.as_view(), name="plans-catalog"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/google/", GoogleAuthView.as_view(), name="auth-google"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/profile/", ProfileUpdateView.as_view(), name="auth-profile"),
    path(
        "auth/change-password/",
        ChangePasswordView.as_view(),
        name="auth-change-password",
    ),
    path(
        "auth/forgot-password/",
        ForgotPasswordView.as_view(),
        name="auth-forgot-password",
    ),
    path(
        "auth/reset-password/confirm/",
        ResetPasswordConfirmView.as_view(),
        name="auth-reset-password-confirm",
    ),
    path("auth/plan/", PlanUpdateView.as_view(), name="auth-plan"),
    path(
        "engagement/me/",
        EngagementProfileView.as_view(),
        name="engagement-me",
    ),
    path(
        "insights/me/",
        UserInsightsSummaryView.as_view(),
        name="insights-me",
    ),
    path(
        "notifications/preferences/",
        NotificationPreferencesView.as_view(),
        name="notifications-preferences",
    ),
    path(
        "devices/register/",
        NotificationDeviceRegisterView.as_view(),
        name="devices-register",
    ),
    path(
        "devices/<int:device_id>/",
        NotificationDeviceDeleteView.as_view(),
        name="devices-delete",
    ),
    path(
        "devices/",
        NotificationDeviceListView.as_view(),
        name="devices-list",
    ),
    path("ask/", AskView.as_view(), name="ask"),
    path("ask/stream/", AskStreamView.as_view(), name="ask-stream"),
    path("guest/ask/", GuestAskView.as_view(), name="guest-ask"),
    path("guest/history/", GuestHistoryView.as_view(), name="guest-history"),
    path(
        "guest/history/reset/",
        GuestHistoryResetView.as_view(),
        name="guest-history-reset",
    ),
    path(
        "guest/recent-questions/",
        GuestRecentQuestionsView.as_view(),
        name="guest-recent-questions",
    ),
    path("follow-ups/", FollowUpGenerateView.as_view(), name="follow-ups"),
    path(
        "analytics/events/",
        AnalyticsEventIngestView.as_view(),
        name="analytics-events",
    ),
    path(
        "analytics/summary/",
        AnalyticsSummaryView.as_view(),
        name="analytics-summary",
    ),
    path("mantra/", MantraView.as_view(), name="mantra"),
    # Quote art generation
    path("quote-art/styles/", QuoteArtStylesView.as_view(), name="quote-art-styles"),
    path("quote-art/generate/", QuoteArtView.as_view(), name="quote-art-generate"),
    path("quote-art/featured/", FeaturedQuotesView.as_view(), name="quote-art-featured"),
    path(
        "eval/retrieval/",
        RetrievalEvalView.as_view(),
        name="eval-retrieval",
    ),
    path("daily-verse/", DailyVerseView.as_view(), name="daily-verse"),
    path(
        "daily-verse/history/",
        DailyVerseHistoryView.as_view(),
        name="daily-verse-history",
    ),
    # Chapter and verse browsing
    path("chapters/", ChapterListView.as_view(), name="chapters"),
    path(
        "chapters/<int:chapter_number>/",
        ChapterDetailView.as_view(),
        name="chapter-detail",
    ),
    path(
        "verses/<int:chapter>.<int:verse>/note/",
        VerseUserNoteView.as_view(),
        name="verse-user-note",
    ),
    path(
        "verses/<int:chapter>.<int:verse>/",
        VerseDetailView.as_view(),
        name="verse-detail",
    ),
    path("verses/search/", VerseSearchView.as_view(), name="verse-search"),
    path("reading/state/", ReadingStateView.as_view(), name="reading-state"),
    path("reading/verse-open/", ReadingVerseOpenView.as_view(), name="reading-verse-open"),
    path("reading/gita-path/", GitaPathView.as_view(), name="gita-path"),
    path("reading/gita-path/start/", GitaPathStartView.as_view(), name="gita-path-start"),
    path("reading/gita-path/pause/", GitaPathPauseView.as_view(), name="gita-path-pause"),
    path("reading/gita-path/resume/", GitaPathResumeView.as_view(), name="gita-path-resume"),
    path("reading/gita-path/advance/", GitaPathAdvanceView.as_view(), name="gita-path-advance"),
    path("reading/gita-path/abandon/", GitaPathAbandonView.as_view(), name="gita-path-abandon"),
    path("practice/log/", PracticeLogListCreateView.as_view(), name="practice-log"),
    path(
        "practice/meditation-sessions/",
        MeditationSessionLogCreateView.as_view(),
        name="practice-meditation-session",
    ),
    path("japa/commitments/", JapaCommitmentListCreateView.as_view(), name="japa-commitments"),
    path(
        "japa/commitments/<int:pk>/",
        JapaCommitmentDetailView.as_view(),
        name="japa-commitment-detail",
    ),
    path(
        "japa/commitments/<int:pk>/fulfill/",
        JapaCommitmentFulfillView.as_view(),
        name="japa-commitment-fulfill",
    ),
    path(
        "japa/commitments/<int:pk>/sessions/start/",
        JapaSessionStartView.as_view(),
        name="japa-session-start",
    ),
    path("japa/sessions/<int:pk>/pause/", JapaSessionPauseView.as_view(), name="japa-session-pause"),
    path("japa/sessions/<int:pk>/resume/", JapaSessionResumeView.as_view(), name="japa-session-resume"),
    path(
        "japa/sessions/<int:pk>/finish-day/",
        JapaSessionFinishDayView.as_view(),
        name="japa-session-finish-day",
    ),
    path(
        "japa/sessions/<int:pk>/abandon/",
        JapaSessionAbandonView.as_view(),
        name="japa-session-abandon",
    ),
    path("history/me/", ConversationHistoryView.as_view(), {"user_id": "me"}),
    path(
        "history/<str:user_id>/",
        ConversationHistoryView.as_view(),
        name="history",
    ),
    path(
        "conversations/",
        ConversationListCreateView.as_view(),
        name="conversations",
    ),
    path(
        "conversations/<int:conversation_id>/",
        ConversationDetailView.as_view(),
        name="conversation-detail",
    ),
    path(
        "conversations/<int:conversation_id>/messages/",
        ConversationMessagesView.as_view(),
        name="conversation-messages",
    ),
    path(
        "community/posts/<int:post_id>/",
        CommunityPostDetailView.as_view(),
        name="community-post-detail",
    ),
    path(
        "community/posts/",
        CommunityPostListCreateView.as_view(),
        name="community-posts",
    ),
    path("feedback/", FeedbackView.as_view(), name="feedback"),
    path("support/", SupportRequestView.as_view(), name="support"),
    path("support/tickets/", SupportTicketListView.as_view(), name="support-tickets"),
    path(
        "saved-reflections/",
        SavedReflectionListCreateView.as_view(),
        name="saved-reflections",
    ),
    path(
        "saved-reflections/<int:reflection_id>/",
        SavedReflectionDetailView.as_view(),
        name="saved-reflection-detail",
    ),
    path("chat-ui/", ChatUIView.as_view(), name="chat-ui"),
    # Shareable answer cards
    path(
        "answers/share/",
        SharedAnswerCreateView.as_view(),
        name="answers-share",
    ),
    # Payment / Subscription endpoints
    path("payments/create-order/", CreateOrderView.as_view(), name="create-order"),
    path(
        "payments/checkout/bridge/",
        PaymentCheckoutBridgeView.as_view(),
        name="payment-checkout-bridge",
    ),
    path("payments/history/", PaymentHistoryView.as_view(), name="payment-history"),
    path("payments/status/", PaymentStatusUpdateView.as_view(), name="payment-status-update"),
    path("payments/verify/", VerifyPaymentView.as_view(), name="verify-payment"),
    path("payments/webhook/", RazorpayWebhookView.as_view(), name="razorpay-webhook"),
    path("subscription/status/", SubscriptionStatusView.as_view(), name="subscription-status"),
    path("sadhana/programs/", SadhanaProgramListView.as_view(), name="sadhana-programs"),
    path(
        "sadhana/programs/<slug:slug>/",
        SadhanaProgramDetailView.as_view(),
        name="sadhana-program-detail",
    ),
    path(
        "sadhana/programs/<slug:slug>/days/<int:day_number>/",
        SadhanaDayDetailView.as_view(),
        name="sadhana-day-detail",
    ),
    path(
        "sadhana/programs/<slug:slug>/days/<int:day_number>/complete/",
        SadhanaDayCompleteView.as_view(),
        name="sadhana-day-complete",
    ),
    path("sadhana/me/", SadhanaMeView.as_view(), name="sadhana-me"),
    path("practice/tags/", PracticeTagListView.as_view(), name="practice-tags"),
    path("practice/workflows/", PracticeWorkflowListView.as_view(), name="practice-workflows"),
    path(
        "practice/workflows/me/",
        PracticeWorkflowMeView.as_view(),
        name="practice-workflows-me",
    ),
    path(
        "practice/workflows/<slug:slug>/",
        PracticeWorkflowDetailView.as_view(),
        name="practice-workflow-detail",
    ),
]
