# Generated by Django 5.2.13 on 2026-04-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='itr_uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('detected_type', models.CharField(blank=True, choices=[('ITR1', 'ITR-1'), ('ITR4', 'ITR-4'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('classifying', 'Classifying'), ('extracting', 'Extracting'), ('review_required', 'Review Required'), ('approved', 'Approved'), ('exported', 'Exported'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('review_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('account_type', models.CharField(blank=True, max_length=64, null=True)),
                ('nominate_for_refund', models.CharField(blank=True, max_length=16, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='documents.document')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TDSDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('deductor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tan_pan', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.CharField(blank=True, max_length=32, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('total_tax_deducted', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('amount_claimed_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('carry_forward', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_details', to='documents.document')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('normalized_value', models.TextField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('source_bbox', models.JSONField(blank=True, null=True)),
                ('extraction_method', models.CharField(blank=True, max_length=64, null=True)),
                ('requires_review', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='documents.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'field_name'), name='uniq_document_field_name')],
            },
        ),
    ]
