# Generated by Django 5.2.13 on 2026-04-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='native_text_char_count',
            field=models.PositiveIntegerField(blank=True, help_text='Characters extracted from the PDF text layer (before OCR fallback).', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='used_ocr_fallback',
            field=models.BooleanField(default=False, help_text='True if Tesseract OCR was used because native text was too short.'),
        ),
    ]
