# Generated by Django 5.2.13 on 2026-04-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_native_text_char_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('classifying', 'Classifying'), ('extracting', 'Extracting'), ('review_required', 'Review Required'), ('approved', 'Approved'), ('exported', 'Exported'), ('failed', 'Failed')], default='uploaded', max_length=32),
        ),
    ]
