# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_alter_tdsdetail_head_of_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="upload_source",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("json", "JSON")],
                default="pdf",
                max_length=10,
            ),
        ),
    ]
