# Generated by Django 5.2.13 on 2026-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_upload_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='native_text_char_count',
            field=models.PositiveIntegerField(blank=True, help_text='For JSON imports: UTF-8 source length in characters.', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_source',
            field=models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON')], default='json', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='used_ocr_fallback',
            field=models.BooleanField(default=False, help_text='Legacy: was OCR used on a PDF upload (retained for old rows).'),
        ),
    ]
