"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-+pn9do9yu-&_qscmk570yk_%@o1z0z8h#ki=)zy9xr18ykf4#u",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "true").lower() == "true"

# Used by CanonicalHostRedirectMiddleware (prod only)
CANONICAL_HOST = os.getenv("CANONICAL_HOST", "askbhagavadgita.co.in").strip()

# Production security settings
if not DEBUG:
    # Fly terminates TLS at the edge and forwards requests to the app.
    # Trust the forwarded scheme to avoid infinite https redirect loops.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "testserver",
    ".onrender.com",  # Render.com hosting
    ".fly.dev",  # Fly.io default domain
    ".ngrok-free.app",  # Allow ngrok tunnels for local testing
    ".ngrok.io",
    ".trycloudflare.com",  # Allow cloudflared tunnels for local testing
    "askbhagavadgita.co.in",
    "www.askbhagavadgita.co.in",
]
extra_hosts = os.getenv("ALLOWED_HOSTS", "")
if extra_hosts:
    ALLOWED_HOSTS.extend(
        [host.strip() for host in extra_hosts.split(",") if host.strip()],
    )

CSRF_TRUSTED_ORIGINS = []
# Allow ngrok origins in debug mode for local internet-accessible testing
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        "https://*.ngrok-free.app",
        "https://*.ngrok.io",
        "https://*.trycloudflare.com",
    ])
else:
    # Custom domain(s) served via Fly (TLS terminated at the edge)
    CSRF_TRUSTED_ORIGINS.extend([
        "https://askbhagavadgita.co.in",
        "https://www.askbhagavadgita.co.in",
    ])
extra_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if extra_csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend(
        [
            origin.strip()
            for origin in extra_csrf_origins.split(",")
            if origin.strip()
        ],
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'guide_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'guide_api.middleware.CanonicalHostRedirectMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

def _postgres_db_from_url(url: str) -> dict:
    """Parse DATABASE_URL postgres DSN into Django DATABASES shape."""
    parsed = urlparse(url)
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote((parsed.path or "").lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "localhost",
        "PORT": str(parsed.port or "5432"),
    }


database_url = os.getenv("DATABASE_URL", "").strip()
if database_url.startswith(("postgres://", "postgresql://")):
    DATABASES = {
        "default": _postgres_db_from_url(database_url),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")
OPENAI_EMBEDDING_MODEL = os.getenv(
    "OPENAI_EMBEDDING_MODEL",
    "text-embedding-3-small",
)
ENABLE_SEMANTIC_RETRIEVAL = os.getenv(
    "ENABLE_SEMANTIC_RETRIEVAL",
    "true",
).lower() == "true"
ENABLE_PGVECTOR_RETRIEVAL = os.getenv(
    "ENABLE_PGVECTOR_RETRIEVAL",
    "false",
).lower() == "true"
PGVECTOR_TABLE = os.getenv(
    "PGVECTOR_TABLE",
    "guide_api_verse_embedding_index",
)
PGVECTOR_EMBEDDING_DIM = int(
    os.getenv("PGVECTOR_EMBEDDING_DIM", "1536"),
)
PGVECTOR_PROBES = int(
    os.getenv("PGVECTOR_PROBES", "10"),
)
DISABLE_ALL_QUOTAS = os.getenv(
    "DISABLE_ALL_QUOTAS",
    "false",
).lower() == "true"
ASK_LIMIT_FREE_DAILY = int(os.getenv("ASK_LIMIT_FREE_DAILY", "3"))
ASK_LIMIT_PLUS_DAILY = int(os.getenv("ASK_LIMIT_PLUS_DAILY", "0"))
ASK_LIMIT_PRO_DAILY = int(os.getenv("ASK_LIMIT_PRO_DAILY", "0"))

# Monthly ask quotas (Free = 100/month, Paid plans have higher limits)
ASK_LIMIT_FREE_MONTHLY = int(os.getenv("ASK_LIMIT_FREE_MONTHLY", "100"))
ASK_LIMIT_PLUS_MONTHLY = int(os.getenv("ASK_LIMIT_PLUS_MONTHLY", "200"))
ASK_LIMIT_PRO_MONTHLY = int(os.getenv("ASK_LIMIT_PRO_MONTHLY", "500"))

# Deep-mode entitlement controls
ENABLE_FREE_DEEP_MODE = os.getenv(
    "ENABLE_FREE_DEEP_MODE",
    "false",
).lower() == "true"
ASK_LIMIT_PLUS_DEEP_MONTHLY = int(
    os.getenv("ASK_LIMIT_PLUS_DEEP_MONTHLY", "40"),
)
ASK_LIMIT_PRO_DEEP_MONTHLY = int(
    os.getenv("ASK_LIMIT_PRO_DEEP_MONTHLY", "180"),
)

# Per-plan LLM output token caps (controls cost per ask)
MAX_OUTPUT_TOKENS_FREE = int(os.getenv("MAX_OUTPUT_TOKENS_FREE", "500"))
MAX_OUTPUT_TOKENS_PLUS = int(os.getenv("MAX_OUTPUT_TOKENS_PLUS", "800"))
MAX_OUTPUT_TOKENS_PRO = int(os.getenv("MAX_OUTPUT_TOKENS_PRO", "1200"))

# Per-plan retrieval context verse limits
MAX_CONTEXT_VERSES_FREE = int(os.getenv("MAX_CONTEXT_VERSES_FREE", "3"))
MAX_CONTEXT_VERSES_PLUS = int(os.getenv("MAX_CONTEXT_VERSES_PLUS", "5"))
MAX_CONTEXT_VERSES_PRO = int(os.getenv("MAX_CONTEXT_VERSES_PRO", "6"))

# Hard caps to limit runaway LLM cost
MAX_ASK_INPUT_CHARS = int(os.getenv("MAX_ASK_INPUT_CHARS", "2200"))
MAX_ASK_ACTIONS = int(os.getenv("MAX_ASK_ACTIONS", "3"))
MAX_VERSE_REFERENCES = int(os.getenv("MAX_VERSE_REFERENCES", "3"))

# Razorpay Payment Settings
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "")
RAZORPAY_WEBHOOK_SECRET = os.getenv("RAZORPAY_WEBHOOK_SECRET", "")

# Subscription Pricing (in paise for INR, cents for USD)
SUBSCRIPTION_PRICE_PLUS_INR = int(
    os.getenv("SUBSCRIPTION_PRICE_PLUS_INR", "19900"),
)  # ₹199/month (India)
SUBSCRIPTION_PRICE_PLUS_USD = int(
    os.getenv("SUBSCRIPTION_PRICE_PLUS_USD", "349"),
)  # $3.49/month
SUBSCRIPTION_PRICE_PRO_INR = int(
    os.getenv("SUBSCRIPTION_PRICE_PRO_INR", "49900"),
)  # ₹499/month (India)
SUBSCRIPTION_PRICE_PRO_USD = int(
    os.getenv("SUBSCRIPTION_PRICE_PRO_USD", "849"),
)  # $8.49/month

# Backward-compatible aliases used by older tests/clients.
SUBSCRIPTION_PRICE_INR = SUBSCRIPTION_PRICE_PRO_INR
SUBSCRIPTION_PRICE_USD = SUBSCRIPTION_PRICE_PRO_USD
SUPPORT_EMAIL = os.getenv("SUPPORT_EMAIL", "support@askbhagavadgita.com")
GOOGLE_SITE_VERIFICATION = os.getenv("GOOGLE_SITE_VERIFICATION", "")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
}
