# Generated by Django 5.2.13 on 2026-04-18 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('page_view', 'Page view'), ('pricing_view', 'Pricing view'), ('signup_start', 'Signup page')], max_length=24)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('first_utm_source', models.CharField(blank=True, max_length=64)),
                ('first_utm_medium', models.CharField(blank=True, max_length=64)),
                ('first_utm_campaign', models.CharField(blank=True, max_length=64)),
                ('last_utm_source', models.CharField(blank=True, max_length=64)),
                ('last_utm_medium', models.CharField(blank=True, max_length=64)),
                ('last_utm_campaign', models.CharField(blank=True, max_length=64)),
                ('last_path', models.CharField(blank=True, max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
