"""Human-readable labels for canonical field names (review UI + PDF)."""
from __future__ import annotations

from apps.extractors import canonical as C

FIELD_LABELS: dict[str, str] = {
    C.ASSESSEE_NAME: "Name of Assessee",
    C.PAN: "PAN",
    C.ASSESSMENT_YEAR: "Assessment Year",
    C.ITR_TYPE: "ITR Type",
    C.FILING_DATE: "Date of filing",
    C.FINANCIAL_YEAR: "Financial Year",
    C.ORIGINAL_OR_REVISED: "Original / Revised",
    C.FILING_SECTION: "Section filed under",
    C.STATUS: "Status",
    C.FILING_STATUS: "Filing Status",
    C.REGIME: "Tax Regime",
    C.RESIDENTIAL_STATUS: "Residential Status",
    C.FATHER_NAME: "Father's Name",
    C.DATE_OF_BIRTH: "Date of Birth",
    C.GENDER: "Gender",
    C.AADHAAR: "Aadhaar",
    C.EMAIL: "E-mail",
    C.MOBILE: "Mobile",
    C.ADDRESS: "Address",
    C.FILING_DUE_DATE: "Due date for filing",
    C.SEVENTH_PROVISO_139: "Seventh proviso to section 139",
    C.VERIFICATION_PLACE: "Place (verification)",
    C.EMPLOYER_CATEGORY: "Employer category",
    C.INCOME_SALARY: "Income from Salary",
    C.INCOME_BUSINESS_PROFESSION: "Income from Business & Profession",
    C.INCOME_HOUSE_PROPERTY: "Income from House Property",
    C.INCOME_OTHER_SOURCES: "Income from Other Sources",
    C.OTHER_SOURCE_NATURE: "Nature of income (Other Sources)",
    C.OS_INTEREST_SAVINGS: "Saving Bank Interest (Other Sources)",
    C.OS_INTEREST_TERM_DEPOSIT: "FDR / Term Deposit Interest (Other Sources)",
    C.OS_INTEREST_REFUND: "Interest on Income Tax Refund (Other Sources)",
    C.BUSINESS_DEPRECIATION_BOOKS: "Depreciation as per Books (Business)",
    C.BUSINESS_DEPRECIATION_IT: "Depreciation as per Income Tax (Business)",
    C.TOTAL_HEAD_WISE_INCOME: "Total of Head-wise Income",
    C.CURRENT_YEAR_LOSSES_ADJUSTMENT: "Current Year Losses Adjustment",
    C.BALANCE_AFTER_CYLA: "Balance After CYLA",
    C.BROUGHT_FORWARD_LOSS_SETOFF: "Brought Forward Loss Set-off",
    C.GROSS_TOTAL_INCOME: "Gross Total Income",
    C.DEDUCTION_80C: "Deduction u/s 80C",
    C.DEDUCTION_80D: "Deduction u/s 80D",
    C.DEDUCTION_80TTA: "Deduction u/s 80TTA",
    C.DEDUCTION_80G: "Deduction u/s 80G",
    C.TOTAL_DEDUCTIONS: "Total Deductions (Chapter VI-A)",
    C.TOTAL_INCOME: "Total Income",
    C.ROUNDED_TOTAL_INCOME: "Total Income Rounded u/s 288A",
    C.BUSINESS_NAME: "Business name (trade name)",
    C.BUSINESS_CODE: "Business code / nature of activity",
    C.BP_TURNOVER_44AD: "Turnover / receipts — prescribed electronic modes (44AD E1a)",
    C.BP_RECEIPTS_OTHER_MODE_44AD: "Turnover / receipts — other modes (44AD E1b)",
    C.BP_PRESUMPTIVE_44AD: "Presumptive income u/s 44AD (Schedule BP)",
    C.SALARY_GROSS: "Gross salary",
    C.SALARY_AS_PER_SECTION_17: "Salary as per section 17",
    C.NET_SALARY_UTILITY: "Net salary (utility)",
    C.ALLOWANCES_EXEMPT_US10_TOTAL: "Allowances exempt u/s 10 (total)",
    C.STANDARD_DEDUCTION_US16IA: "Standard deduction u/s 16(ia)",
    C.DEDUCTION_US16_TOTAL: "Deduction u/s 16",
    C.ENTERTAINMENT_ALLOWANCE_US16II: "Entertainment allowance u/s 16(ii)",
    C.PROFESSIONAL_TAX_US16III: "Professional tax u/s 16(iii)",
    C.TAX_NORMAL_RATES: "Tax at Normal Rates",
    C.TAX_PAYABLE_ON_TOTAL_INCOME: "Tax Payable on Total Income",
    C.CESS: "Health & Education Cess",
    C.REBATE_87A: "Rebate u/s 87A",
    C.TAX_RELIEF: "Relief of tax (where applicable)",
    C.INTEREST_234A: "Interest u/s 234A",
    C.INTEREST_234B: "Interest u/s 234B",
    C.INTEREST_234C: "Interest u/s 234C",
    C.FEE_234F: "Fee u/s 234F",
    C.TDS_FROM_SALARY: "TDS on salary",
    C.TDS_OTHER_THAN_SALARY: "TDS other than salary",
    C.GROSS_TAX_LIABILITY: "Gross Tax Liability",
    C.NET_TAX_LIABILITY: "Net Tax Liability",
    C.ADVANCE_TAX: "Advance Tax",
    C.SELF_ASSESSMENT_TAX: "Self Assessment Tax",
    C.TDS_TOTAL: "Total TDS on Income",
    C.TCS_TOTAL: "TCS",
    C.TAXES_PAID_TOTAL: "Taxes Paid",
    C.REFUND_AMOUNT: "Amount Refundable (as per utility / demand)",
    C.REFUND_PRE_288B: "Amount Refundable (taxes paid minus net tax, pre-u/s 288B)",
    C.ROUNDED_REFUND_AMOUNT: "Amount Refundable Rounded u/s 288B",
    C.DEMAND_AMOUNT: "Tax Payable / Demand",
    C.TOTAL_TAX_PLUS_INTEREST: "Total tax + interest (utility)",
}


def label_for(name: str) -> str:
    return FIELD_LABELS.get(name, name.replace("_", " ").title())
